# Generated by Django 5.2.1 on 2025-05-30 09:41

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_examplemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum_file',
            field=models.FileField(blank=True, help_text='Upload curriculum file (PDF, DOC, PPT, etc. - max 50MB)', null=True, upload_to=courses.models.curriculum_file_path, validators=[courses.models.validate_curriculum_file]),
        ),
        migrations.AddField(
            model_name='course',
            name='file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
